using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using System.Security;
using System.Windows.Resources;

[assembly: AssemblyVersion("2.1.1.0")]
[assembly: AssemblyAssociatedContentFile("assets/servicesconfigbad.json")]
[assembly: AssemblyAssociatedContentFile("assets/servicesconfiggood.json")]
[assembly: AssemblyAssociatedContentFile("webview2loader.dll")]
[assembly: AssemblyCompany("RustTweaker")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyFileVersion("2.1.1.0")]
[assembly: AssemblyInformationalVersion("2.1.1+8c148b64488a0090ed3a8796b5b5227cf337e661")]
[assembly: AssemblyProduct("RustTweaker")]
[assembly: AssemblyTitle("RustTweaker")]
[assembly: TargetPlatform("Windows7.0")]
[assembly: SupportedOSPlatform("Windows7.0")]
[module: RefSafetyRules(11)]
